trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"

  - task: Npm@1
    displayName: "NPM: Install Extension Dependencies"
    inputs:
      workingDir: .
      verbose: false

  - task: Npm@1
    displayName: "NPM: Build Extension"
    inputs:
      command: custom
      workingDir: .
      verbose: false
      customCommand: "run build"

  - task: Npm@1
    displayName: "NPM: Install Task Dependencies"
    inputs:
      workingDir: tasks/UploadPortalHtmlReport
      verbose: false

  - script: npm test
    displayName: "NPM: Test Upload Task"
    workingDirectory: tasks/UploadPortalHtmlReport

  - task: PackageAzureDevOpsExtension@2
    displayName: "TFX: Package Extension"
    inputs:
      rootFolder: .
      publisherId: joneja09
      extensionName: "HTML Report Portal"
      extensionVisibility: private
      extensionPricing: free
      patternManifest: "azure-devops-extension.json"
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))

  - task: PackageAzureDevOpsExtension@2
    displayName: "TFX: Package Extension Dev"
    inputs:
      rootFolder: .
      publisherId: joneja09
      extensionId: "html-report-portal"
      extensionTag: dev
      extensionName: "HTML Report Portal Dev"
      extensionVersion: "1.3.$(Build.BuildId)"
      updateTasksVersion: true
      extensionVisibility: private
      extensionPricing: free
      patternManifest: "azure-devops-extension.json"
    condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'master'))

  - task: CopyFiles@2
    displayName: "Copy Files"
    inputs:
      SourceFolder: "$(System.DefaultWorkingDirectory)"
      Contents: "*.vsix"
      TargetFolder: "$(Build.ArtifactStagingDirectory)/results"
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)/results"
    condition: succeededOrFailed()
